# NumPy Basics: Arrays and Vectorized Computation

In [ ]:
import numpy as np
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))
np.set_printoptions(precision=4, suppress=True)

In [ ]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [ ]:
%time for _ in range(10): my_arr2 = my_arr * 2
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

## The NumPy ndarray: A Multidimensional Array Object

In [1]:
import numpy as np
# Generate some random data
data = np.random.randn(2, 3)
data

array([[1.60228382, 0.05455899, 0.05989068],
       [0.55063544, 1.26969532, 1.39191864]])

In [3]:
print(data * 10)
data + data

[[16.02283815  0.54558987  0.59890684]
 [ 5.50635437 12.69695321 13.91918636]]


array([[3.20456763, 0.10911797, 0.11978137],
       [1.10127087, 2.53939064, 2.78383727]])

In [4]:
data.shape

(2, 3)

In [5]:
data.dtype

dtype('float64')

### Creating ndarrays

In [ ]:
"""
• ndarray, an efficient multidimensional array providing fast array-oriented arithmetic
operations and flexible broadcasting capabilities.
• Mathematical functions for fast operations on entire arrays of data without having
to write loops.
• Tools for reading/writing array data to disk and working with memory-mapped
files.
• Linear algebra, random number generation, and Fourier transform capabilities.
• A C API for connecting NumPy with libraries written in C, C++, or FORTRAN.
"""

In [6]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [7]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
arr2.ndim
arr2.shape

(2, 4)

In [9]:
print(arr1.dtype)
arr2.dtype

float64


dtype('int64')

In [11]:
np.zeros(10)
print(np.zeros((3, 6)))
np.empty((2, 3, 2))

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


array([[[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 1.58817677e-052]],

       [[7.11818641e-091, 9.17103570e-072],
        [5.50852873e+169, 3.53988978e-057],
        [3.99910963e+252, 1.46030983e-319]]])

In [12]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Data Types for ndarrays

In [14]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
print(arr1.dtype)
arr2.dtype

float64


dtype('int32')

In [15]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
float_arr = arr.astype(np.float64)
float_arr.dtype

int64


dtype('float64')

In [16]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [17]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [18]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [19]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

### Arithmetic with NumPy Arrays

In [21]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr)
print(arr * arr)
arr - arr

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]


array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
print(1 / arr)
arr ** 0.5

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [23]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

### Basic Indexing and Slicing

In [26]:
arr = np.arange(10)
print(arr)
print(arr[5])
print(arr[5:8])
arr[5:8] = 12
arr

[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]


array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [28]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [29]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [30]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [33]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d)
arr2d[2]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([7, 8, 9])

In [32]:
print(arr2d[0][2])
arr2d[0, 2]

3


3

In [34]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [35]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
old_values = arr3d[0].copy()
arr3d[0] = 42
print(arr3d)
arr3d[0] = old_values
print(arr3d)

[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [38]:
arr3d[1, 0]

array([7, 8, 9])

In [39]:
x = arr3d[1]
print(x)
x[0]

[[ 7  8  9]
 [10 11 12]]


array([7, 8, 9])

#### Indexing with slices

In [40]:
print(arr)
arr[1:6]

[ 0  1  2  3  4 64 64 64  8  9]


array([ 1,  2,  3,  4, 64])

In [41]:
print(arr2d)
arr2d[:2]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [43]:
arr2d[1, :2]

array([4, 5])

In [44]:
arr2d[:2, 2]

array([3, 6])

In [45]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [46]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### Boolean Indexing

In [47]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(names)
data

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']


array([[-1.00064448,  0.7541548 , -0.14366298,  0.05577578],
       [ 1.36601091,  0.53044275, -1.74253379,  1.70226775],
       [ 1.0197626 ,  0.09773693, -0.74406015, -0.64925797],
       [ 1.1826482 , -0.48090342, -1.15589295, -0.83413398],
       [ 0.40651567, -0.14417809, -1.54577224, -0.7209511 ],
       [-0.11980347,  1.47484742, -1.91077896, -0.55122439],
       [-2.25660366, -0.65840761,  0.10094034,  0.65607321]])

In [48]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [49]:
data[names == 'Bob']

array([[-1.00064448,  0.7541548 , -0.14366298,  0.05577578],
       [ 1.1826482 , -0.48090342, -1.15589295, -0.83413398]])

In [50]:
print(data[names == 'Bob', 2:])
data[names == 'Bob', 3]

[[-0.14366298  0.05577578]
 [-1.15589295 -0.83413398]]


array([ 0.05577578, -0.83413398])

In [51]:
print(names != 'Bob')
data[~(names == 'Bob')]

[False  True  True False  True  True  True]


array([[ 1.36601091,  0.53044275, -1.74253379,  1.70226775],
       [ 1.0197626 ,  0.09773693, -0.74406015, -0.64925797],
       [ 0.40651567, -0.14417809, -1.54577224, -0.7209511 ],
       [-0.11980347,  1.47484742, -1.91077896, -0.55122439],
       [-2.25660366, -0.65840761,  0.10094034,  0.65607321]])

In [ ]:
cond = names == 'Bob'
data[~cond]

In [52]:
mask = (names == 'Bob') | (names == 'Will')
print(mask)
data[mask]

[ True False  True  True  True False False]


array([[-1.00064448,  0.7541548 , -0.14366298,  0.05577578],
       [ 1.0197626 ,  0.09773693, -0.74406015, -0.64925797],
       [ 1.1826482 , -0.48090342, -1.15589295, -0.83413398],
       [ 0.40651567, -0.14417809, -1.54577224, -0.7209511 ]])

In [53]:
data[data < 0] = 0
data

array([[0.        , 0.7541548 , 0.        , 0.05577578],
       [1.36601091, 0.53044275, 0.        , 1.70226775],
       [1.0197626 , 0.09773693, 0.        , 0.        ],
       [1.1826482 , 0.        , 0.        , 0.        ],
       [0.40651567, 0.        , 0.        , 0.        ],
       [0.        , 1.47484742, 0.        , 0.        ],
       [0.        , 0.        , 0.10094034, 0.65607321]])

In [54]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [1.36601091, 0.53044275, 0.        , 1.70226775],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 1.47484742, 0.        , 0.        ],
       [0.        , 0.        , 0.10094034, 0.65607321]])

### Fancy Indexing

In [55]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [56]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [57]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [59]:
arr = np.arange(32).reshape((8, 4))
print(arr)
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


array([ 4, 23, 29, 10])

In [60]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

### Transposing Arrays and Swapping Axes

In [61]:
arr = np.arange(15).reshape((3, 5))
print(arr)
arr.T

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [62]:
arr = np.random.randn(6, 3)
print(arr)
np.dot(arr.T, arr)

[[ 1.61375819 -0.2676759  -1.41304454]
 [-0.58454206 -0.69527905 -0.01338503]
 [ 0.04068706  0.26014311  1.0412073 ]
 [-0.0845734  -1.019572    0.70003461]
 [-0.87923046 -0.80072584 -0.41544819]
 [-0.2580509  -0.62152481 -0.04487081]]


array([[ 3.79434951,  0.93567639, -1.91247508],
       [ 0.93567639,  2.68971982,  0.30521994],
       [-1.91247508,  0.30521994,  3.74564572]])

In [63]:
arr = np.arange(16).reshape((2, 2, 4))
print(arr)
arr.transpose((1, 0, 2))

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [ ]:
arr
arr.swapaxes(1, 2)

## Universal Functions: Fast Element-Wise Array Functions

In [64]:
arr = np.arange(10)
print(arr)
print(np.sqrt(arr))
np.exp(arr)

[0 1 2 3 4 5 6 7 8 9]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [65]:
x = np.random.randn(8)
y = np.random.randn(8)
print(x)
print(y)
np.maximum(x, y)

[-0.14513027 -0.59830511 -1.95010518 -0.61074557 -1.27676668 -0.02412436
 -0.92987632  1.59399891]
[-0.51508214 -0.07093078 -1.69574649 -0.24250877 -0.90742465  1.03749796
  1.20455169 -0.9477909 ]


array([-0.14513027, -0.07093078, -1.69574649, -0.24250877, -0.90742465,
        1.03749796,  1.20455169,  1.59399891])

In [66]:
arr = np.random.randn(7) * 5
print(arr)
remainder, whole_part = np.modf(arr)
print(remainder)
whole_part

[ 2.49026339  5.35785102  7.30935084 -7.09840955  3.72938558  0.99718586
  2.94095252]
[ 0.49026339  0.35785102  0.30935084 -0.09840955  0.72938558  0.99718586
  0.94095252]


array([ 2.,  5.,  7., -7.,  3.,  0.,  2.])

In [67]:
arr
np.sqrt(arr)
np.sqrt(arr, arr)
arr

/var/folders/h7/2089f0v15x7bxpvfmd61kbhc0000gn/T/ipykernel_56465/2118003981.py:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)
/var/folders/h7/2089f0v15x7bxpvfmd61kbhc0000gn/T/ipykernel_56465/2118003981.py:3: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr, arr)


array([1.57805684, 2.31470323, 2.70358111,        nan, 1.93116172,
       0.99859194, 1.71492056])

## Array-Oriented Programming with Arrays

In [ ]:
points = np.arange(-5, 5, 0.01) # 1000 equally spaced points
xs, ys = np.meshgrid(points, points)
ys

In [ ]:
z = np.sqrt(xs ** 2 + ys ** 2)
z

In [ ]:
import matplotlib.pyplot as plt
plt.imshow(z, cmap=plt.cm.gray); plt.colorbar()
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")

In [ ]:
plt.draw()

In [ ]:
plt.close('all')

### Expressing Conditional Logic as Array Operations

In [68]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [69]:
result = [(x if c else y)
          for x, y, c in zip(xarr, yarr, cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [70]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [71]:
arr = np.random.randn(4, 4)
arr
arr > 0
np.where(arr > 0, 2, -2)

array([[ 2,  2, -2, -2],
       [ 2,  2,  2, -2],
       [-2,  2,  2, -2],
       [-2, -2, -2,  2]])

In [72]:
np.where(arr > 0, 2, arr) # set only positive values to 2

array([[ 2.        ,  2.        , -1.55008873, -0.8640935 ],
       [ 2.        ,  2.        ,  2.        , -0.33678794],
       [-0.34081786,  2.        ,  2.        , -1.88626453],
       [-0.36804   , -0.90987244, -1.09644224,  2.        ]])

### Mathematical and Statistical Methods

In [73]:
arr = np.random.randn(5, 4)
print(arr)
print(arr.mean())
print(np.mean(arr))
arr.sum()

[[-1.26088245 -0.7482134  -0.14969204  0.60615524]
 [-0.08773465  2.13424596 -0.41989506 -0.36011862]
 [ 0.91009796 -0.99842077  0.4313361  -0.39237107]
 [ 0.74832867 -2.72650625  0.78595906  0.84284282]
 [-1.86310486 -1.04512001  1.74834277 -0.73388911]]
-0.128931985136023
-0.128931985136023


-2.57863970272046

In [74]:
print(arr.mean(axis=1))
arr.sum(axis=0)

[-0.38815816  0.31662441 -0.01233944 -0.08734392 -0.4734428 ]


array([-1.55329532, -3.38401447,  2.39605083, -0.03738074])

In [75]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28])

In [77]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print(arr)
print(arr.cumsum(axis=0))
arr.cumprod(axis=1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2]
 [ 3  5  7]
 [ 9 12 15]]


array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]])

### Methods for Boolean Arrays

In [ ]:
arr = np.random.randn(100)
(arr > 0).sum() # Number of positive values

In [ ]:
bools = np.array([False, False, True, False])
bools.any()
bools.all()

### Sorting

In [ ]:
arr = np.random.randn(6)
arr
arr.sort()
arr

In [ ]:
arr = np.random.randn(5, 3)
arr
arr.sort(1)
arr

In [ ]:
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.05 * len(large_arr))] # 5% quantile

### Unique and Other Set Logic

In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

In [ ]:
sorted(set(names))

In [ ]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

## File Input and Output with Arrays

In [ ]:
arr = np.arange(10)
np.save('some_array', arr)

In [ ]:
np.load('some_array.npy')

In [ ]:
np.savez('array_archive.npz', a=arr, b=arr)

In [ ]:
arch = np.load('array_archive.npz')
arch['b']

In [ ]:
np.savez_compressed('arrays_compressed.npz', a=arr, b=arr)

In [ ]:
!rm some_array.npy
!rm array_archive.npz
!rm arrays_compressed.npz

## Linear Algebra

In [ ]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x
y
x.dot(y)

In [ ]:
np.dot(x, y)

In [ ]:
np.dot(x, np.ones(3))

In [ ]:
x @ np.ones(3)

In [ ]:
from numpy.linalg import inv, qr
X = np.random.randn(5, 5)
mat = X.T.dot(X)
inv(mat)
mat.dot(inv(mat))
q, r = qr(mat)
r

## Pseudorandom Number Generation

In [ ]:
samples = np.random.normal(size=(4, 4))
samples

In [ ]:
from random import normalvariate
N = 1000000
%timeit samples = [normalvariate(0, 1) for _ in range(N)]
%timeit np.random.normal(size=N)

In [ ]:
np.random.seed(1234)

In [ ]:
rng = np.random.RandomState(1234)
rng.randn(10)

## Example: Random Walks

In [ ]:
import random
position = 0
walk = [position]
steps = 1000
for i in range(steps):
    step = 1 if random.randint(0, 1) else -1
    position += step
    walk.append(position)

In [ ]:
plt.figure()

In [ ]:
plt.plot(walk[:100])

In [ ]:
np.random.seed(12345)

In [ ]:
nsteps = 1000
draws = np.random.randint(0, 2, size=nsteps)
steps = np.where(draws > 0, 1, -1)
walk = steps.cumsum()

In [ ]:
walk.min()
walk.max()

In [ ]:
(np.abs(walk) >= 10).argmax()

### Simulating Many Random Walks at Once

In [ ]:
nwalks = 5000
nsteps = 1000
draws = np.random.randint(0, 2, size=(nwalks, nsteps)) # 0 or 1
steps = np.where(draws > 0, 1, -1)
walks = steps.cumsum(1)
walks

In [ ]:
walks.max()
walks.min()

In [ ]:
hits30 = (np.abs(walks) >= 30).any(1)
hits30
hits30.sum() # Number that hit 30 or -30

In [ ]:
crossing_times = (np.abs(walks[hits30]) >= 30).argmax(1)
crossing_times.mean()

In [ ]:
steps = np.random.normal(loc=0, scale=0.25,
                         size=(nwalks, nsteps))

## Conclusion